######################################################################
# Automatically generated by qmake (3.1) Wed Apr 1 20:11:24 2026
######################################################################

QT += gui widgets core
TEMPLATE = app
TARGET = fold
INCLUDEPATH += .
DESTDIR = build
MOC_DIR = build
OBJECTS_DIR = build

CONFIG += link_pkgconfig
PKGCONFIG += libpodofo poppler-qt6

CONFIG+=fontAwesomeFree
include(QtAwesome/QtAwesome.pri)

HEADERS += mainwindow.hpp \
        mergepage.hpp \
        splitpage.hpp \
        homepage.hpp \
        reorderpage.hpp \
        deletepage.hpp \
        awesome.hpp

SOURCES += main.cpp \
        mainwindow.cpp \
        mergepage.cpp \
        splitpage.cpp \
        homepage.cpp \
        deletepage.cpp \
        reorderpage.cpp
