######################################################################
# Automatically generated by qmake (3.1) Wed Apr 1 20:11:24 2026
######################################################################

QT += gui widgets core
TEMPLATE = app
TARGET = fold
INCLUDEPATH += .
DESTDIR = build
MOC_DIR = build
OBJECTS_DIR = build

CONFIG += link_pkgconfig
PKGCONFIG += libpodofo

HEADERS += mainwindow.hpp \
        mergepage.hpp \
        splitpage.hpp \
        homepage.hpp

SOURCES += main.cpp \
        mainwindow.cpp \
        mergepage.cpp \
        splitpage.cpp \
        homepage.cpp
